### ISSUE TITLE
Slow performance with axis aligned ray

### ISSUE THREAD

**Issue by stephomi** [madmann91/bvh#21] opened 2020-12-14 18:57 UTC
Great lib!

However I get very low performance when casting axis-aligned rays.
It takes 7 seconds or so, instead of ~10ms (~30k rays on a ~3M meshes, the mesh has axis aligned triangles as well).

When I add a small epsilon to the ray to make sure all components are non null, things become fast again.

I didn't dig the issue further.
I can just say there is no division by 0 here https://github.com/madmann91/bvh/blob/183da93f21f9738e1bbd0ef11943fc20159f124a/include/bvh/triangle.hpp#L96

**Comment by madmann91** [comment] 2020-12-15 10:12
Hello, and thank you for the bug report. Are you on x86? If so, can you try adding the following code before doing anything (you need to include `x86intrin.h`)?
```cpp
_mm_setcsr(_mm_getcsr() | (_MM_FLUSH_ZERO_ON | _MM_DENORMALS_ZERO_ON));
```
Regardless if this solves your issue or not, could you point me to more information to reproduce the bug? And maybe point me to a scene I could use to reproduce this?

**Comment by madmann91** [comment] 2020-12-15 12:02
I'm working on a fix. It seems that `bvh::RobustNodeIntersector` is not affected by the issue. You can try using that in the mean time. To do that, create the single ray traverser with that as a template parameter:
```cpp
bvh::SingleRayTraverser<Bvh, 64, bvh::RobustNodeIntersector<Bvh>>
```

**Comment by madmann91** [comment] 2020-12-15 12:35
This issue should now be fixed by 3b2f3d0 (and following bug fix 354de26). This performance problem was caused by too many false positives in the ray-node intersection during BVH traversal. The fix introduced here will just prevent the traversal from processing nodes in that case, but keep in mind that `bvh::FastNodeIntersector` is anyway an intersector that loses precision for ray directions that are close to zero. That should not be a problem in most use cases, but you may want to switch to the robust intersector when you observe artefacts due to the ray missing the geometry. Could you please check that the issue is fixed on your end as well?

**Comment by stephomi** [comment] 2020-12-15 13:21
Yes it works!

I'm using the bvh to project a mesh onto another, so the rays are generated for each vertices (the ray length are very short as the 2 meshes are somewhat identical).

**Comment by madmann91** [comment] 2020-12-15 13:23
Alright, then I'm closing this.

**Closed by madmann91** 2020-12-15 13:23 UTC
