### ISSUE TITLE
Missing triangles in output

### ISSUE THREAD

**Issue by cignox1** [madmann91/bvh#28] opened 2021-01-20 23:39 UTC
Hello, me again!
In the test scene I'm currently using there are a few triangles apparently missing. I was sure it was a problem with the scene file (exported from blender), with Assimp (the lib I use to load the scene) or my code. I've started to play a bit with the mesh in blender (simplify, remove vertices, triangulate etc), then by exporting to different file formats. Nothing changed. Then I tried to render the scene with my BIH, and, to my surprise, the scene was fine.
That's how it looks with my BIH
![BIH](https://user-images.githubusercontent.com/76952351/105253864-9c3b3700-5b80-11eb-8ff5-53c649ad110f.jpg)

and with the BVH:
![BVH](https://user-images.githubusercontent.com/76952351/105253874-9fcebe00-5b80-11eb-954a-3fcc72eb0d40.jpg)
(sorry for the bad quality, hope will do anyway). Please note the fireplace, or the corner opposite to the point of view. There are a couple more, but you can't see it in the that image (I can of course provide you with better ones).
I understand that this is not much to work with, but thought to report it should you be interested in analyzing the issue. Let mw know if you want the collada/gltf/blend file of the scene.

That's how I create the bvh:

		void Preprocess()
		{
			//bvh::SweepSahBuilder<bvh::Bvh<real>> builder(bvh);
			bvh::LocallyOrderedClusteringBuilder<bvh::Bvh<real>, int>  builder(bvh);

			//Adapt data format
			bvh::BoundingBox<real>* bboxes = new bvh::BoundingBox<real>[shapes.size()];
			bvh::Vector3<real>* centers = new bvh::Vector3<real>[shapes.size()];

			qlaabox<real> worldbb;
			for (int i = 0; i < shapes.size(); ++i) {
				qlaabox<real> bb = shapes[i].origShape->GetBoundingBox();
				bboxes[i] = bvh::BoundingBox<real>(MasterBVHPrimitive::toVector3(bb.min), MasterBVHPrimitive::toVector3(bb.max));
				worldbb.Union(bb);
				centers[i] = MasterBVHPrimitive::toVector3(bb.Center());
			}
			
			builder.build(bvh::BoundingBox<real>(MasterBVHPrimitive::toVector3(worldbb.min), MasterBVHPrimitive::toVector3(worldbb.max)), bboxes, centers, shapes.size());
			bvh::LeafCollapser<bvh::Bvh<real>> collapser(bvh);
			collapser.collapse();
			std::cout << "Radius: " << builder.search_radius << std::endl;
			std::cout << "Shapes count : " << shapes.size() << std::endl;
			//std::cout << "Tree depth : " << TreeDepth(root) << std::endl;
			std::cout << "Node count : " << bvh.node_count << std::endl;
			//std::cout << "Leaf count : " << LeafCount(root) << std::endl;
			/*std::cout << "Average primitives/leaf : " << ((real)ShapesCount(root)) / LeafCount(root) << std::endl;
			std::cout << "Empty leaves : " << EmptyLeaves(root) << std::endl;
			std::cout << "Max shapes : " << MaxShapes(root) << std::endl;*/
		}

And the traversal code:

		bool Intersect(const ray<vector4<real>>& r, SurfacePoint& hitdesc) const
		{
			// Intersect a ray with the data structure
			Ray ray = MasterBVHPrimitive::toRay(r);
			
			bvh::ClosestPrimitiveIntersector<bvh::Bvh<real>, MasterBVHPrimitive> primitive_intersector(bvh, shapes.data());
			bvh::SingleRayTraverser<bvh::Bvh<real>> traverser(bvh);

			auto hit = traverser.traverse(ray, primitive_intersector);
			if (hit)
			{
				hitdesc = hit->intersection.hitdesc;
				return true;
			}
			else
				return false;
		}
Thank you and regards,
Alessandro

**Comment by madmann91** [comment] 2021-01-21 09:10
Hello, and thank you for the bug report! Do you observe the same problem with all builders, or just `bvh::LocallyOrderedClustering`? As a side note, I am pretty sure that using `int` instead of an unsigned integer type for the Morton code type like you do is going to produce errors. I am going to add some static assertions to catch that.

**Comment by cignox1** [comment] 2021-01-21 09:59
Thank you for the hint about the int issue, will check that for sure this afternoon. I will also check that my custom intersector is correct and doesn't lose triangles here and there :D

**Comment by cignox1** [comment] 2021-01-21 10:20
And of course I will also try with other builder and let you know...

**Comment by madmann91** [comment] 2021-01-21 11:10
Note that if you have an OBJ file for the scene you can try it with the benchmark tool provided in the `test` directory:
```
benchmark scene.obj --builder locally_ordered_clustering --eye x y z --dir x y z --up x y z
```

**Comment by cignox1** [comment] 2021-01-21 22:39
Hello,
I've been able to test with:
			//bvh::SweepSahBuilder<bvh::Bvh<real>> builder(bvh);
			//bvh::LocallyOrderedClusteringBuilder<bvh::Bvh<real>, unsigned int>  builder(bvh);
			bvh::LinearBvhBuilder<bvh::Bvh<real>, unsigned int> builder(bvh);

SweepSahBuilder better than LocallyOrderedClusteringBuilder, LinearBvhBuilder better than SweepSahBuilder. With SweepSahBuilder that's the result:
![image](https://user-images.githubusercontent.com/76952351/105420420-9e64ca80-5c40-11eb-893c-81e290438d17.png)

the lamp is never 100% correct (see my BIH render) and there are a couple missing triangles. I tried with BinnedSahBuilder but it was suspiciously. So slow, it might have been testing each triangle for each ray (pixels were slowing being printed, 1 for every second or so). I suppose I was using it the wrong way. I could not test SpatialSplitBvhBuilder because it requires an additional array of primitives and I have not been able to provide it (it's late + I don't use c++ very often since 10 years or so + I'm not familiar at all with 11). If needed, no problems in writing some code tomorrow to make it work (maybe a copy ctor for my triangle would do the trick).
I might as well try your benchmark, if I find some more time to compile it.

Let me know if you want some more test.
Regards,
Alessandro

**Comment by madmann91** [comment] 2021-01-21 23:56
Can you provide the implementation for `MasterBVHPrimitive`? Can you also say if `real` is `float` or `double`?

If all the BVH builders exhibit this issue, chances are the problem stems from either the data fed to the BVH building algorithm, or from the primitive intersection routine, or both. I cannot reproduce this issue, even using your scene, which I suppose is the living room scene from the Mc Guire CG archive (https://casual-effects.com/g3d/data10/index.html#mesh21):

![render](https://user-images.githubusercontent.com/8089474/105427040-914dd880-5c4c-11eb-8e67-03caf9eff3b8.png)

As an additional note, using the centers of the triangles gives better BVHs than using the centers of the bounding boxes like you do in the example above. I think the simplest option if you want to debug the issue is to just use `bvh::Triangle`, by copying your shapes into an array or `std::vector` of triangles. Then, you can work out which pieces are not working properly by replacing the bits of the `bvh::Triangle` data structure one by one.

As an added bonus, the data layout of `bvh::Triangle` is carefully crafted to speed up the intersection routine too, so it will most likely make things run faster too. Moreover, `bvh::Triangle` is compatible with `bvh::compute_bounding_boxes_and_centers()` and `bvh::compute_bounding_boxes_union()`, which you can use to compute the bounding box and centers of each triangle, and the global bounding box, in parallel.

**Comment by cignox1** [comment] 2021-01-22 07:22
Hello, and thank you again! (beautiful render btw, just out of curiosity: how long did it take to render, and at which resolution?)
I will most try to test with your triangle (not sure about replacing my class though, I'd like to leave at least *some* of my code in my renderer XD XD). Real is float.
I will post my MasterBVHPrimitive implementation here, but don't want you to lose more time if the bug is in my code, I'll first test as you suggested. I don't think the problem is in the intersection routine, as it works when using BIH... well, we will see. I'll also use the primitive centers.
Thank you again

**Comment by madmann91** [comment] 2021-01-22 16:29
If you have some code online I'd be happy to have a look and even debug this myself. I don't think that's going to take too much of my time. I suggested using `bvh::Triangle` only for debugging: If it works with it then maybe you can determine the parts of the code that are faulty. To be clear, I am almost certain that this is a bug in your code given that I can render that same scene and that there are tests to verify the correctness of various parts of the library, but it still is technically possible that this is a bug in this library because of some unusual setup or scene input, so hopefully using `bvh::Triangle` will also help clearing that last doubt.

If you cannot share the code for `MasterBVHPrimitive` then I cannot really help debugging beyond giving general advice such as:

- Trying a simpler scene (e.g. Cornell Box) to see if the problem appears there,
- Making sure that the primitive data (and their order in the array) does not change between the call to `build()` and `traverse()`,
- Making sure the conversion functions (to/from vector or bounding boxes of your program and this library) are correct,
- Making sure your rays are correct (in particular, the tmin/tmax values).

The rendered picture I linked above took around 1min to render on my laptop, using Path Tracing with MIS, at a resolution of 1080x720. It's not completely converged as you can see from the remaining noise.

**Comment by cignox1** [comment] 2021-01-22 16:44
Hello,

>>If you have some code online I'd be happy to have a look and even debug this myself.
No code online, unfortunately :-( My code is relatively clean for the most part, but the project is a mess and with a lot of dependancies like assimp, FreeImage, boost and Oidn (is an old project I abandoned 10 years ago due little free time. I got back to it without really thinking to invest much time, but its just too entertaining to work on it XD). I will most certainly try with you Triangle as soon as possible and report here the results.

>>The rendered picture I linked above took around 1min to render on my laptop, using Path Tracing with MIS, at a resolution of 1080x720
Simply Amazing!
>>It's not completely converged as you can see from the remaining noise.
Oidn would turn it in a perfectly clean image. It does wonders, and it's straightforward to integrate...

I'll let you know...

**Comment by cignox1** [comment] 2021-01-23 00:39
Hello again!

I had the following tests: first I switched to primitive centroid instead than bbox. Then I noticed that I could kind of reproduce similar issues with my BIH by setting my epsilon too small or too large and tried playing a bit with those values. Then I had a try with real = double. I found and fixed a bug in my MasterBVHPrimitive.
As these quick things did not work, I used your Triangle implementation, first by creating one on the fly in my Triangle intersection routine, delegate the intersection computation, and fill my intersection structure accordingly, and then by adding a new member variable of type Triangle to my QLTriangle. Nothing changed:
![image](https://user-images.githubusercontent.com/76952351/105562191-90cf4380-5d19-11eb-8b8b-f74a13b37df5.png)

I've noticed that today (and well before I started playing with the code) the wrong features are different: in particular, the fireplace looks fine. I can't explain why.

My MasterBVHPrimitive is as follows:

`	using Vector3 = bvh::Vector3<real>;
	using Triangle = bvh::Triangle<real>;
	using Ray = bvh::Ray<real>;

	struct MasterBVHPrimitive {
		QLShape* origShape;

		struct Intersection {
			real t;
			SurfacePoint hitdesc;
			// Required member: returns the distance along the ray
			real distance() const { return t; }
		};

		// Required type: the floating-point type used
		using ScalarType = real;
		// Required type: the intersection data type returned by the intersect() method
		using IntersectionType = Intersection;

		MasterBVHPrimitive() : origShape(NULL) {}
		MasterBVHPrimitive(QLShape* origShape) : origShape(origShape) {}

		// Required member: returns the center of the primitive
		Vector3 center() const {
			return toVector3(((QLTriangle*)origShape)->GetTriangle()->GetCentroid());
		}

		// Required member: returns a bounding box for the primitive (tighter is better)
		bvh::BoundingBox<real> bounding_box() const {
			qlaabox<real> bb = origShape->GetBoundingBox();
			return bvh::BoundingBox<real>(toVector3(bb.min), toVector3(bb.max));
		}

		// Required member: computes the intersection between a ray and the primitive
		std::optional<Intersection> intersect(const Ray& r) const {
			ray<vector4<real>> qlr = toQLRay(r);
			Intersection intersection;
			if (origShape->Intersect(qlr, intersection.hitdesc))
			{
				intersection.t = intersection.hitdesc.point.distance;
				return std::make_optional<Intersection>(intersection);
			}
			else
				return {};
		}

		static const bvh::Vector3<real> toVector3(const vector4<real>& v) { return bvh::Vector3<real>(v.x, v.y, v.z); }
		static const vector4<real> toQLVector(const bvh::Vector3<real>& v) { return vector4<real>(v[0], v[1], v[2]); }
		static const bvh::Ray<real> toRay(const ray<vector4<real>>& r) {
			return 	bvh::Ray<real>(toVector3(r.origin), toVector3(r.direction), r.mindistance, r.maxdistance);
		}
		static const ray<vector4<real>> toQLRay(const bvh::Ray<real>& r) {
			return ray<vector4<real>>(toQLVector(r.origin), toQLVector(r.direction), r.tmin, r.tmax);
		}

	};`

That's my intersection code, which I think is pretty much correct (it is also almost 15 years old :D):
`		bool Intersect(const ray<vector4<T>>& r, T &ucoord, T &vcoord) const
		{
			assert(data != NULL);

			const vector4<T> b = VERTEX(_B) - VERTEX(_A);
			const vector4<T> c = VERTEX(_C) - VERTEX(_A);

			//Find the determinant
			vector4<T> pvec = r.direction.Cross(c);
			T det = b.Dot3(pvec);

			//IF CULL
		/*	if(det < T(Q_EPSILON)) return false;
			
			//U parameter
			vector4<T> tvec = r.origin - VERTEX(_A);
			T u = tvec.Dot3(pvec);
			if(u < T(0.0) || u > det) return false;

			//V parameter
			vector4<T> qvec = tvec.Cross(b);
			T v = r.direction.Dot3(qvec);
			if(v < T(0.0) || u + v > det) return false;

			//T parameter
			T t = c.Dot3(qvec);

			T inv_det = T(1.0) / det;
			t *= inv_det;
			u *= inv_det;
			v *= inv_det;

			/*ALTRIMENTI*/
			if(IsZero(det)) return false;

			T inv_det = T(1.0) / det;

			vector4<T> tvec = r.origin - VERTEX(_A);

			//U parameter
			T u =  tvec.Dot3(pvec) * inv_det;
			if(u < T(0.0) || u > T(1.0)) return false;

			//V parameter
			vector4<T> qvec = tvec.Cross(b);
			T v = r.direction.Dot3(qvec) * inv_det;
	
			if(v < T(0.0) || u + v > T(1.0)) return false;

			//T parameter
			T t = c.Dot3(qvec) * inv_det;

			/*END IF*/
			if(t < r.maxdistance && t > T(0))
			{	
				r.maxdistance = t;
				ucoord = u;
				vcoord = v;
				return true;
			}
			return false;
		}`

In the next couple of days I'll try to test with your Triangle class as you describe.
Thank you again and best regards,

**Comment by madmann91** [comment] 2021-01-23 09:09
Not sure if the errors you see are related, but you use `0` instead of `ray.mindistance` in the intersection routine. This means you might report intersections when there are none. Additionally, if you use an epsilon value in `isZero()`, you will get artefacts for long and thin triangles. Here's what I get with your intersection routine and the following definition for `isZero()`:
```
bool isZero(Scalar x) { return std::fabs(x) < Scalar(1.e-5); }
```
![render_incorrect](https://user-images.githubusercontent.com/8089474/105573795-618ff500-5d60-11eb-8bb5-ca5272834e38.png)

Adjusting the epsilon only changes the scale at which the problem appears. Here with `1e-7`, zoomed in on the radio:

![render_zoom](https://user-images.githubusercontent.com/8089474/105573887-f09d0d00-5d60-11eb-8188-076d28b9b78e.png)

I recommend using an intersection routine that is designed to reject NaNs and does not need an epsilon value. The trick is to remember that any comparison between `a` and `b` (in floating point) returns `false` if either `a` or `b` is a NaN (assuming IEEE-754, which is more than reasonable). The intersection routine in this library follows this principle.

I don't think the artefacts you report are due to your intersection routine, though, since I only see them on small objects and not in the same places as you do. I still think something might be wrong during construction. I also thought that it could be related to ray offsets.  Do you offset your rays from surfaces when bouncing? If you don't use the `tmin` of the ray, I suppose you use the normal? Something could be wrong there.

Finally, are the artefacts you observe exactly the same for each run? If they differ, if only a bit, it might make sense to use `valgrind` to determine if you have any illegal memory access or uninitialized memory that could explain this behavior.

**Comment by cignox1** [comment] 2021-01-23 14:15
Thank you for the hints about the intersection method. As said, that one of the olders part of the program, I might gave skipped some details (i.e. checking distance against 0 instead than min). I'll consider different algorithms in the future,

Now, look at that, this is really, really weird and I could not come out with an explanation not involving exotic quantum effects:
![image](https://user-images.githubusercontent.com/76952351/105580404-75e9e700-5d8c-11eb-8ddd-1533ed0b4cc2.png)

That's how it looks in Blender:
![image](https://user-images.githubusercontent.com/76952351/105580442-b77a9200-5d8c-11eb-8926-c488567f7e97.png)

The "holes" are not missing triangles. It looks like they are kind of a boolean operations (front triangle - back triangle) or something like that. Same thing for other 2 holes (which aren't holes, I've tried changing the "no hit/background" color, but they are always black. I'm trying to understand if they are shading issues i.e. normal or something like that)
In addition, the same exact problem, with the same holes, also when moving the pov:
![image](https://user-images.githubusercontent.com/76952351/105580592-92d2ea00-5d8d-11eb-86a6-003f4cc71c4e.png)

I don't think this is something related to the intersection routine: as you said, something related to the bvh building.  I'll keep investigating...

**Comment by madmann91** [comment] 2021-01-23 15:07
It looks like the indices are incorrect. I have seen this type of artefact when converting the quads of a scene into triangles and messing up the order of the indices.

**Comment by cignox1** [comment] 2021-01-23 15:17
I'm starting from scratch, that is from the original obj file, imported in a new blender scene. I have still a few things I'd like to check, ie the geometric normals: my shading normals look fine, usually, but if I use the geometric ones (even only to calculate the offset from the hit point) I get a mess.

**Comment by cignox1** [comment] 2021-01-23 23:34
Hello, just wanted you to know that I could get some pretty decent results by starting from the obj file instead than from the collada one:
![image](https://user-images.githubusercontent.com/76952351/105616914-9fc9fa80-5dda-11eb-8135-dacc8b0a9445.png)

a few hours of debugging: the lib I use to load input files was passing me wrong materials for some of the meshes, some other meshes had no normals etc. Still, a few holes and if I use collada thing did not change much. I've noticed that a couple tris were missing even while using my BIH when I left the assimp lib generate normals and tangent space, while by skipping that prepass things are nice when using obj (not yet when using collada, but I think it's a matter of the wrong material. Maybe):
![image](https://user-images.githubusercontent.com/76952351/105617002-98572100-5ddb-11eb-9b60-6b0c37bb26dd.png)
(noiser because waaaay slower).
Not sure what is happening. I'd say there are a couple thing playing at the same time (normals, materials, maybe something with the epsilon annoying the BIH traversal?).
I will have another look as soon as possible.
Regards,
Alessandro

**Comment by madmann91** [comment] 2021-01-28 11:47
Hello! Do you have any update? Should I close the issue?

**Comment by cignox1** [comment] 2021-01-28 13:11
Hello, sorry for not having updated the status! Truth is, I could not
identify the true cause: sometimes I was sure it was something in the BVH,
because my BIH was working fine, sometimes I suspected a bug in the mesh
loader, and sometimes I could not help but wondering if there was something
wrong with my shading code.
I've currently disabled culling (now rays intersect triangles on both
sides) and with the current obj living room (and its collada converted
version) It looks like I no longer have these glitches. I did not have much
time to try with other scene/settings however. Please close the issue.
Should I ever see them again, I will report them here (if I can exclude my
code/external libraries).

Thank you again!


Il giorno gio 28 gen 2021 alle ore 12:48 Arsène Pérard-Gayot <
notifications@github.com> ha scritto:

**Comment by madmann91** [comment] 2021-01-28 19:48
Alright, thank you for the update! Closing the issue. Do not hesitate to re-open if required.

**Closed by madmann91** 2021-01-28 19:48 UTC
