### ISSUE TITLE
No intersections when a ray direction value is 0

### ISSUE THREAD

**Issue by AODQ** [madmann91/bvh#9] opened 2020-04-21 00:28 UTC
Right now I see that if I cast rays where ray.x = 0 or ray.z = 0, the BVH tree does not return a triangle. This could affect ray.y but I have not really tried that yet. Adding epsilon in those corner cases fixes the problem but there's probably a better solution.

[BVH tree](https://drive.google.com/open?id=1IVO_cI9UfEzkBCawuxdJuCOZ-1TZrAAJ)
[no BVH tree, just raycast against all triangles](https://drive.google.com/open?id=17optEcp5081p6J6eXJMsRGf3g87LjULd)
[intersection test always returns true, closest intersector](https://drive.google.com/open?id=120SE58q5ZrFb1tYPpqB6ZilqxL4aeQUY)
[intersection test always returns true, any intersector](https://drive.google.com/open?id=1Y-RinLOXnxkk4fU4yZNngmYzvFHByxby)

In the benchmark, if I force `dir.x = 0` (then normalize afterwards), nothing at all renders to the screen:

benchmark.cpp:121
```
            Ray ray(camera.eye, bvh::normalize(image_u * u + image_v * v + dir));
            ray.direction.values[0] = 0.0f;
            ray.direction = bvh::normalize(ray.direction);
```

[without modification](https://drive.google.com/file/d/1Nc0_yBdV2dyagOOnFQLaql_mtDbnnQsZ/view?usp=sharing)
[setting value to 0.000001f](https://drive.google.com/file/d/1TTrO_o775xJ6tZvowu7ZukAMOuM_cRHB/view?usp=sharing)
[setting value to 0.0f](https://drive.google.com/file/d/1mgwb5EHt1AMtAfZagxazJwLGlgxsuRnx/view?usp=sharing)

This seems to vary by each model, models with high triangle density don't seem to suffer from this issue.

**Comment by madmann91** [comment] 2020-04-21 08:28
This is due to the very nature of the ray-box intersection test, which has to divide by the ray direction. I will check if I can apply the techniques described in [Robust BVH Ray Traversal](https://www.google.com/url?q=http://www.sci.utah.edu/~thiago/papers/robustBVH-v2.pdf&sa=U&ved=2ahUKEwizpryyi_noAhUeAWMBHZ-lCBEQFjAAegQIBBAB&usg=AOvVaw2CYyoDbBVK1rCkKeYPx0Dq).

**Comment by madmann91** [comment] 2020-04-21 11:18
I believe this has been fixed in fe1a1f5ac9d19848be428898a434db4554ee2a38 (but this commit introduces another bug, so please use the latest master instead). I have also introduced a robust mode for the BVH traversal, but you won't need it to fix this bug. It's for large models and precision issues that may arise when looking at highly detailed objects from far away. Could you please close the issue if this is fixed on your side? If not, just update me, and I'll have a look again.

**Comment by madmann91** [comment] 2020-04-22 11:08
I assume that the issue is now fixed on your end. If not, feel free to re-open the issue again.

**Closed by madmann91** 2020-04-22 11:08 UTC
Labels: bug

**Comment by AODQ** [comment] 2020-04-22 16:53
Yes it's fixed, just tested it now. Thank you!
